name: PythonTestMatrix
on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  test_matrix_python:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2019, 'macos-11', 'macos-12', macos-13, macos-14]
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        test: ['example_mem.py', 'example.py', 'example2.py', 'example3.py', 'example4.py']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - uses: actions/checkout@v3
        with:
          sparse-checkout: examples

      - name: Install duckdb
        run: |
          pip install pyarrow
          pip install --upgrade --pre duckdb
          pip install polars
          pip install pandas

      - name: Run minor test
        shell: bash
        run: |
          set PYTHONIOENCODING=utf-8
          python3 examples/${{ matrix.test }}

  test_matrix_python_build:
    if: false
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-2019]
        version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - uses: actions/checkout@v3
        with:
          sparse-checkout: examples

      - name: Install duckdb
        run: |
          pip install build
          pip install --no-binary duckdb --upgrade --pre duckdb

      - name: Run minor test
        shell: bash
        run: |
          python3 examples/example.py

  test_matrix_cli:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2019, 'macos-11', 'macos-12', macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: examples

      - name: Install duckdb
        run: |
          curl https://carlopi.github.io/duckdb-latest/install.sh | bash
          source /home/runner/.bashrc

      - name: Install duckdb2
        run: |
          which duckdb-latest
          duckdb-latest -c "INSTALL spatial; LOAD spatial;"
